# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regist', '0003_auto_20170508_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='sex',
            field=models.BooleanField(choices=[(1, '男'), (0, '女')], max_length=1, verbose_name='性别'),
        ),
    ]
