# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regist', '0004_auto_20170509_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='sex',
            field=models.IntegerField(choices=[(1, '男'), (0, '女')], verbose_name='性别'),
        ),
    ]
