# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='宾馆名称')),
                ('hoteltype', models.CharField(max_length=20, verbose_name='类型')),
                ('address', models.CharField(max_length=30, verbose_name='地址')),
                ('coordinate', models.CharField(max_length=60, verbose_name='地址坐标')),
                ('classtype', models.CharField(max_length=20, verbose_name='房间类型')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='价格')),
                ('start_at', models.DateField(verbose_name='入住日期')),
                ('end_at', models.DateField(verbose_name='离店日期')),
                ('total_time', models.IntegerField(verbose_name='住宿天数')),
                ('description', models.TextField(verbose_name='描述')),
                ('is_active', models.IntegerField(default=True, verbose_name='订购状态')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'db_table': 'hotel_plan',
                'verbose_name': '住宿计划',
                'verbose_name_plural': '住宿计划',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='计划单名称')),
                ('fromcity', models.CharField(max_length=30, verbose_name='出发城市')),
                ('toctiy', models.CharField(max_length=30, verbose_name='目的城市')),
                ('start_at', models.DateField(verbose_name='出发日期')),
                ('back_at', models.DateField(verbose_name='返回日期')),
                ('traffictype', models.IntegerField(verbose_name='交通工具')),
                ('hotletype', models.IntegerField(verbose_name='住宿')),
                ('target', models.CharField(max_length=50, verbose_name='目标地址')),
                ('targetcoordinate', models.CharField(max_length=60, verbose_name='目标地址坐标')),
                ('ifback', models.BooleanField(default=True, verbose_name='是否往返')),
                ('description', models.TextField(verbose_name='描述')),
                ('is_active', models.IntegerField(default=True, verbose_name='计划状态')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'db_table': 'plan',
                'verbose_name': '计划',
                'verbose_name_plural': '计划',
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='Plane_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='航班名称')),
                ('companyname', models.CharField(max_length=50, verbose_name='航空公司')),
                ('planetype', models.CharField(max_length=50, verbose_name='执行机型')),
                ('fromcity', models.CharField(max_length=30, verbose_name='起飞站')),
                ('tocity', models.CharField(max_length=30, verbose_name='落地站')),
                ('start_at', models.DateTimeField(verbose_name='起飞时间')),
                ('arrive_at', models.DateTimeField(verbose_name='落地时间')),
                ('fromstation', models.CharField(max_length=50, verbose_name='起飞机场航站')),
                ('tostation', models.CharField(max_length=50, verbose_name='落地机场航站')),
                ('total_time', models.IntegerField(verbose_name='飞行时间')),
                ('classtype', models.CharField(max_length=20, verbose_name='舱位')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='价格')),
                ('description', models.TextField(verbose_name='描述')),
                ('is_active', models.IntegerField(default=True, verbose_name='订购状态')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('planid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Plan')),
            ],
            options={
                'db_table': 'plane_plan',
                'verbose_name': '飞机计划',
                'verbose_name_plural': '飞机计划',
            },
        ),
        migrations.CreateModel(
            name='Train_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='车次')),
                ('traintype', models.CharField(max_length=20, verbose_name='火车类型')),
                ('fromstation', models.CharField(max_length=30, verbose_name='出发站')),
                ('tostation', models.CharField(max_length=30, verbose_name='到达站')),
                ('start_at', models.DateTimeField(verbose_name='发车时间')),
                ('arrive_at', models.DateTimeField(verbose_name='到站时间')),
                ('total_time', models.IntegerField(verbose_name='行驶时间')),
                ('classtype', models.CharField(max_length=20, verbose_name='席别')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='价格')),
                ('description', models.TextField(verbose_name='描述')),
                ('is_active', models.IntegerField(default=True, verbose_name='订购状态')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('planid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Plan')),
            ],
            options={
                'db_table': 'train_plan',
                'verbose_name': '火车计划',
                'verbose_name_plural': '火车计划',
            },
        ),
        migrations.AddField(
            model_name='hotel_plan',
            name='planid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Plan'),
        ),
    ]
