# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='toctiy',
            new_name='tocity',
        ),
    ]
