# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_auto_20170519_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='宾馆名称')),
                ('hoteltype', models.CharField(max_length=20, verbose_name='类型')),
                ('address', models.CharField(max_length=30, verbose_name='地址')),
                ('coordinate', models.CharField(max_length=60, verbose_name='地址坐标')),
                ('classtype', models.CharField(max_length=20, verbose_name='房间类型')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='价格')),
                ('description', models.TextField(verbose_name='描述')),
            ],
            options={
                'verbose_name_plural': '酒店列表',
                'db_table': 'hotel',
                'verbose_name': '酒店列表',
            },
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='航班名称')),
                ('companyname', models.CharField(max_length=50, verbose_name='航空公司')),
                ('planetype', models.CharField(max_length=50, verbose_name='执行机型')),
                ('fromcity', models.CharField(max_length=30, verbose_name='起飞站')),
                ('tocity', models.CharField(max_length=30, verbose_name='落地站')),
                ('start_at', models.DateTimeField(verbose_name='起飞时间')),
                ('arrive_at', models.DateTimeField(verbose_name='落地时间')),
                ('fromstation', models.CharField(max_length=50, verbose_name='起飞机场航站')),
                ('tostation', models.CharField(max_length=50, verbose_name='落地机场航站')),
                ('total_time', models.IntegerField(verbose_name='飞行时间')),
                ('classtype', models.CharField(max_length=20, verbose_name='舱位')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='价格')),
                ('description', models.TextField(verbose_name='描述')),
            ],
            options={
                'verbose_name_plural': '航班列表',
                'db_table': 'plane',
                'verbose_name': '航班列表',
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='车次')),
                ('traintype', models.CharField(max_length=20, verbose_name='火车类型')),
                ('fromstation', models.CharField(max_length=30, verbose_name='出发站')),
                ('tostation', models.CharField(max_length=30, verbose_name='到达站')),
                ('start_at', models.DateTimeField(verbose_name='发车时间')),
                ('arrive_at', models.DateTimeField(verbose_name='到站时间')),
                ('total_time', models.IntegerField(verbose_name='行驶时间')),
                ('classtype', models.CharField(max_length=20, verbose_name='席别')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='价格')),
                ('description', models.TextField(verbose_name='描述')),
            ],
            options={
                'verbose_name_plural': '火车列表',
                'db_table': 'train',
                'verbose_name': '火车列表',
            },
        ),
    ]
