# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 02:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20170413_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-create_at'], 'verbose_name': '产品类别', 'verbose_name_plural': '产品类别'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-create_at'], 'verbose_name': '产品', 'verbose_name_plural': '产品'},
        ),
    ]
